### ISSUE TITLE
1jupp lehekülg

### ISSUE THREAD

**Issue by juljus** [juljus/vhk-matik-website#10]
lisada tiimi liikmete pildid, piltide kõrvale nimi ja ülesanne

**Comment by tenseoverflow** [comment]
![image](https://github.com/juljus/VHKmatik-Website/assets/36374623/97f1be3d-b341-4e4b-ac77-69b26e630aec)

**Comment by tenseoverflow** [comment]
- [ ] Tiimiliikmete fotod

**Comment by tenseoverflow** [comment]
Closed due to #21
