### ISSUE TITLE
Eelmise aasta meedia klipid. 

### ISSUE THREAD

**Issue by Haavi97** [juljus/vhk-matik-website#16]
Saab lisada meedia klipid ja lingid avalehele. Võib võtta eelmise aasta lehest: https://tiim-mcqueen.eu
Selles samas lehes on palju pilte, mida saab kasutada. 

Äkki @L05311 või @kassjyrilo saab selle võtta.

**Comment by tenseoverflow** [comment]
Hakkasin suurest hoost ise tegelema sellega, need läksid koduleheküljele. Siiski oleks vaja leida parem lahendus nende paigutamisel. Ma varsti pushin oma koodi neumorphismi branchi, siis saame rohkem vestelda sel teemal.
