### ISSUE TITLE
Design Prototype

### ISSUE THREAD

**Issue by tenseoverflow** [juljus/vhk-matik-website#3]
A rudimentary design should be put in place. I propose a simple layout consisting of a homepage and team sites.

Homepage should consist of:

- Hero section
- Sponsor logos
- Teams and their descriptions
- Contact info

We could delegate the layout of the team sites to respective teams. But a basic structure should be put in place for consistency.

If anyone has Figma experience, they could prototype this with me.

**Comment by tenseoverflow** [comment]
Site map (as agreed on Monday's meeting):

- Home
- Team pages seperate dropdown
  - 1Jupp
  - BeeGreen
  - Pink tiim 3
- Contact
- How to sponsor details & donations

**Comment by tenseoverflow** [comment]
Design inspiration:

https://raiku.co/ (This is currently the hottest trend, it seems to me. Clear lines with geometrical grids, minimalistic modern-retro vibe. Almost neobrutalism. Also viewport is fully utilised and used.)
https://muba.edu.ee/ (Loading animation unnecessary)
https://webflow.com/blog/web-design-trends-2023
https://builtin.com/design-ux/neumorphism (This was trendy in 2020-2021, not so today but could be an option)

**Comment by tenseoverflow** [comment]
Colours should probably be based around VHK's logo. A darkish red with gold accent tones. Maybe second colour like gray should be used?

**Comment by tenseoverflow** [comment]
https://www.figma.com/file/A2zIThqwI32Q3rezWVBEqd/Landing-page?type=design&node-id=0-1&mode=design&t=jO3QDrxq6OdCDhEn-0

**Comment by tenseoverflow** [comment]
@juljus https://www.figma.com/file/A2zIThqwI32Q3rezWVBEqd/Landing-page?type=design&node-id=0%3A1&mode=design&t=fU0qIrKf8VqEcw2a-1

**Comment by L05311** [comment]
üldised võimalikud disainid?
https://www.figma.com/file/C9rNSwKPFj4nOWgaOJl9vO/Untitled?type=design&node-id=4%3A143&mode=design&t=N1GlsMJuSfG7MqKz-1

**Comment by tenseoverflow** [comment]
Head disainid! Ma asetaks heading'u tiimipildi peale, et koduleheküljega ühtlasem oleks.
