### ISSUE TITLE
BeeGreen lehekülg

### ISSUE THREAD

**Issue by juljus** [juljus/vhk-matik-website#9]
lisada meeskonna kirjeldus, tiimi liikmete pildid, piltide kõrvale nimi ja ülesanne

**Comment by tenseoverflow** [comment]
Closed due to #21

**Comment by tenseoverflow** [comment]
Sorry, not closed. Forgot there's no team member images.

**Comment by tenseoverflow** [comment]
Team member images was added. Thank you!
